name: Daily Playlist Update

on:
  schedule:
    - cron: '0 3 * * *'  # Her gün 03:00 UTC'de
  workflow_dispatch:

jobs:
  update-playlist:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
        
    - name: Install dependencies
      run: |
        pip install requests pyyaml
        
    - name: Run playlist updater and upload to Dropbox
      env:
        SOURCE_PLAYLIST_URL: ${{ secrets.SOURCE_PLAYLIST_URL }}
        DROPBOX_APP_KEY: ${{ secrets.DROPBOX_APP_KEY }}
        DROPBOX_APP_SECRET: ${{ secrets.DROPBOX_APP_SECRET }}
        DROPBOX_REFRESH_TOKEN: ${{ secrets.DROPBOX_REFRESH_TOKEN }}
      run: python playlist_updater.py
