name: Update umitt

on:
  schedule:
    - cron: '*/5 * * * *' # Her 5 dakikada bir çalışır
  workflow_dispatch: # Manuel tetikleme

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: |
          pip install requests

      - name: Run umitt Script
        run: python umitt.py

      - name: Commit and Push
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          # Yula klasörünü ekle
          git add yula/*.m3u8
          git commit -m "Umit: osi klasörü güncellendi" || exit 0
          git push
